### ISSUE TITLE
Creating the DB diagram

### ISSUE THREAD

**Issue by Douglas-i** [crisJAF/BlueMoon-Ecommerce#14]
Good evening Cris @crisJAF , I need to have the DB diagram ready by this weekend, since it is expected that next week we will start working on the Backend, so we need to have that diagram ready to later create it and not fall behind on the project. I look forward to it. Regards.

DH

**Comment by crisJAF** [comment]
hey dude @Douglas-i 
sry for my late response. Im on vacation and Im barely seing my inbox messages. 
I'll to get it done by tonight

**Comment by Douglas-i** [comment]
Ok @crisJAF , please have it tonight because we can't be late and we have to make up for these two lost days, thank you.

**Comment by crisJAF** [comment]
yaki

**Comment by crisJAF** [comment]
yaki x2
