### ISSUE TITLE
Crear rama de UAT

### ISSUE THREAD

**Issue by crisJAF** [crisJAF/BlueMoon-Ecommerce#7]
Hey, douglas. hope you're doing fine. 

I wrote the title on Spanish as I know you barely understand English. I feel sorry that you were raised in that village called Masatepe. 

I'm happy you got onboarded in this new project called "Chambear en sistemas deagratis"! 

Feel free to reach out to me any time you need some help. 

Greetings

Cristopher Avendano. 

By the way, please create the fucking new UAT branch

**Comment by Douglas-i** [comment]
@crisJAF Buenas noches, favor de facilitarme en nombre que tendra rama o si solo se llamara "UAT", quedo atento. Saludos

**Comment by crisJAF** [comment]
what that fuck is that language? i dont get a shit 

if you meant the name of the new branch, it should be "t-PivotIntegracionUAT"

Thanks

**Comment by Douglas-i** [comment]
@crisJAF The branch "t-PivotIntegracionUAT" piece of scrotum is created
